import type { Metadata } from "next";
import { Hanken_Grotesk, Instrument_Serif } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/common/theme-provider";
import { cn } from "@/lib/utils";
import OnekoCat from "@/components/common/oneko-car";

const hkGrotesk = Hanken_Grotesk({
  weight: ["400"],
  style: "normal",
  subsets: ["latin"],
  variable: "--font-hk-grotesk",
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  weight: ["400"],
  style: "normal",
  subsets: ["latin"],
  variable: "--font-instrument-serif",
});

export const metadata: Metadata = {
  title: "Priyanshu Kayarkar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "h-full antialiased font-sans bg-background/50",
          "[&_*::selection]:bg-[#121212] [&_*::selection]:text-[#0BC5B3]",
          "dark:[&_*::selection]:bg-[#04201B] dark:[&_*::selection]:text-[#0BC5B3]",
          hkGrotesk.className,
          instrumentSerif.variable,
        )}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <OnekoCat />
        </ThemeProvider>
      </body>
    </html>
  );
}
